version: '3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - /srv/dev-disk-by-uuid-b032144c-1b53-4062-9736-a42af80f5aa8/docker_dane/vaultwarden:/data/
    restart: always
    ports:
      - "8800:80"
    environment:
      - DOMAIN=https://bitwarden.jojeadmin.pl
      - ADMIN_TOKEN=YourReallyStrongAdminPasswordHereOrToken
