version: '3.3'
services:
    portainer-ce:
        ports:
            - '8000:8000'
            - '9443:9443'
        container_name: portainer
        environment:
          - PUID=1001
          - PGID=100
          - TZ=Europe/Warsaw
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - 'CHANGE_TO_COMPOSE_DATA_PATH/portainer/portainer_data:/data'
        image: 'portainer/portainer-ce:latest'
